#!/bin/bash
echo "Copying .vimrc to $HOME/.vimrc"
cp .vimrc $HOME/.vimrc

if [[ -d "$HOME/.vim/bundle" ]] && [[ -d "$HOME/.vim/bundle" ]]; then
    echo "Pathogen already installed"
else
    echo "Installing Pathogen (for installing plugins)"
    mkdir -p $HOME/.vim/autoload $HOME/.vim/bundle
    curl -LSso $HOME/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
fi

cd $HOME/.vim/bundle

echo "Installing NERDTree"
if [[ -d "nerdtree" ]]; then 
    echo "NERDTree already installed"; 
else
    git clone https://github.com/scrooloose/nerdtree.git
fi

echo "Installing HackerNews"
if [[ -d "vim-hackernews" ]]; then
    echo "HackerNews already installed"
else
    git clone https://github.com/ryanss/vim-hackernews
fi

echo "Installing flake8"
if [[ -d "vim-flake8" ]]; then
    echo "Flake8 already installed"
else
    git clone https://github.com/nvie/vim-flake8
fi
