#!/bin/bash
echo "Copying .gitconfig to $HOME/.gitconfig"
cp .gitconfig $HOME/.gitconfig

echo "Copying .vimrc to $HOME/.vimrc"
cp .vimrc $HOME/.vimrc

if ! /usr/bin/curl -V; then
    echo "Need to install curl first (apt-get install curl)"
    exit 1
fi

if [[ -d "$HOME/.vim/bundle" ]] && [[ -d "$HOME/.vim/bundle" ]]; then
    echo "Pathogen already installed"
else
    echo "Installing Pathogen (for installing plugins)"
    mkdir -p $HOME/.vim/autoload $HOME/.vim/bundle
    /usr/bin/curl -LSso $HOME/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
fi

cd $HOME/.vim/bundle

echo "Installing NERDTree"
if [[ -d "nerdtree" ]]; then
    echo "NERDTree already installed";
else
    /usr/bin/git clone https://github.com/scrooloose/nerdtree.git
fi

echo "Installing Jedi Autocompletion"
if [[ -d "jedi-vim" ]]; then
	echo "Jedi already installed";
else
	/usr/bin/git clone --recursive https://github.com/davidhalter/jedi-vim.git
fi

echo "Installing solarized"
if [[ -d "vim-colors-solarized" ]]; then
    echo "Solarized already installed"
else
    /usr/bin/git clone https://github.com/altercation/vim-colors-solarized.git
fi

echo "Setting up bash prompt"
echo -e "parse_git_branch() {\n\tgit branch 2> /dev/null " \
"| sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'\n}" >> $HOME/.bash_profile
echo 'export PS1="\u@\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "' \
>> $HOME/.bash_profile
echo "Setting up terminal"
echo "export TERM=xterm-256color" >> $HOME/.bash_profile
