#!/bin/bash
if ! /usr/bin/curl -V; then
    echo "Need to install curl first (apt-get install curl)"
    exit 1
fi

echo "Copying .tmux.config to $HOME/.tmux.config"
cp .tmux.conf $HOME/.tmux.conf

echo "Copying .gitconfig to $HOME/.gitconfig"
cp .gitconfig $HOME/.gitconfig

echo "Copying .vimrc to $HOME/.vimrc"
cp .vimrc $HOME/.vimrc

# Bash profile (login shell should just check if there is a bashrc and if there is 
# then source it
echo "Setting up bash prompt, source ~/.bashrc after complete!"
cp .bashrc $HOME/.bashrc

echo "Copying cscope_maps.vim to $HOME/.vim/plugin"
mkdir -p $HOME/.vim/plugin
cp cscope_maps.vim $HOME/.vim/plugin/

if [[ -d "$HOME/.vim/bundle" ]] && [[ -d "$HOME/.vim/bundle" ]]; then
    echo "Pathogen already installed"
else
    echo "Installing Pathogen (for installing plugins)"
    mkdir -p $HOME/.vim/autoload $HOME/.vim/bundle
    /usr/bin/curl -LSso $HOME/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
fi

cd $HOME/.vim/bundle

echo "Installing NERDTree"
if [[ -d "nerdtree" ]]; then
    echo "NERDTree already installed";
else
    /usr/bin/git clone https://github.com/scrooloose/nerdtree.git
fi

echo "Installing Syntastic"
if [[ -d syntastic ]]; then 
    echo "Syntastic already installed";
else
    git clone --depth=1 https://github.com/vim-syntastic/syntastic.git 
fi

echo "Installing Solarized"
if [[ -d "vim-colors-solarized" ]]; then
    echo "Solarized already installed"
else
    /usr/bin/git clone https://github.com/altercation/vim-colors-solarized.git
fi

cd $HOME/
echo "Installing fzf"
if [[ -d ".fzf" ]]; then
	echo "Fuzzy finder already installed"
else
	/usr/bin/git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
	$HOME/.fzf/install
fi
